version: '2'
services:
  rabbit:
    image: rabbitmq:3.9-management
    hostname: rabbit
    container_name: demo-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
      RABBITMQ_DEFAULT_VHOST: '/'
    ports:
      - '15672:15672'
      - '5672:5672'
    labels:
      NAME: 'rabbit'
